### PR TITLE
Additions to CMakeLists.txt to better organize information in IDEs

### PR DESCRIPTION
**Pull request by jdsierral**
In general is just adding some organization instructions so that folders in an IDE show up properly.
Notable details include adding header files to source files: This is important so that an IDE can build "Counterpart" relationships between .h files and .cpp files
Formats were also separated as they are later used to move all those targets into a general Targets folder

Tested this in Xcode (It also seems to be working properly in VS2019 but couldn't build because of Faust dependencies)

Most of the changes come from suggestions on [this](https://forum.juce.com/t/cmake-examples-in-xcode/42188/4) discussion.

### CODE REVIEW

**Comment by jdsierral** [comment]
I did a general code review suggesting changes to implement more modern C++ practices such as smart pointers. The rest were general things that should be showing as warnings in any case.

**Comment by jdsierral** [comment]
I also removed empty `argv` in favor `nullptr` and whenever there are conditionals on returns simplified them to match the real intention of the code

**Comment by glocq** [comment]
Thanks a lot for the detailed info, it's great for learning to have a personalized code review like that. I still have a few issues and questions.
* Why remove AUv3? Does it not compile?
* Why add the header files to the list of source files? Don't they get included in the `.cpp` files anyway?
* Unfortunately the plugin now crashes when I attempt to compile a Faust program. I think it is linked to the `nullptr` --- I had previously tried using an empty array, and it crashed too. Seems like we need at least an array with an empty string (might be something we should tell the Faust folks?)

**Comment by glocq** [comment]
Ah yes, I just realized you were the one who added AUv3 in the first place. I am letting you deal with the MacOS specific stuff indeed.
I just merged your changes! Thank you for your work. Looking forward to the parameter stuff if you do it :)

**Pull request closed without merging**
